apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: traefik
    version: 37.3.0
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
