apiVersion: v2
appVersion: 4.13.6
description: Dependency-Track is an intelligent Component Analysis platform that allows
  organizations to identify and reduce risk in the software supply chain.
home: https://github.com/DependencyTrack/dependency-track
icon: https://avatars.githubusercontent.com/u/40258585
maintainers:
- email: nscuro@protonmail.com
  name: nscuro
  url: https://github.com/nscuro
name: dependency-track
sources:
- https://github.com/DependencyTrack/helm-charts/tree/main/charts/dependency-track
type: application
version: 0.40.0
