---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dependency-track

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: dependency-track
    version: 0.40.0
    repo: https://dependencytrack.github.io/helm-charts
    releaseName: dependency-track
    namespace: dependency-track
    valuesFile: values.yaml
